module.exports = class Api_Controller {
  static getWeekdays(req, res) {
    const weekdays = {
      weekdays: [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thrusday",
        "Friday",
        "Saturday",
        "Sunday",
      ],
    };
    res.status(200).json(weekdays);
  }

  static getSportsList(req, res) {
    const sportList = [
      "Football",
      "Voleyball",
      "Basketball",
      "Rugby",
      "Tennis",
    ];
    res.status(200).json({ sport_list: sportList.sort() });
  }

  static getCities(req, res){
    //cities and towns in Ireland
    const cities = [
      "Abbeyfeale",
      "Abbeyleix",
      "Ardee",
      "Arklow",
      "Artane",
      "Ashbourne",
      "Athboy",
      "Athenry",
      "Athlone",
      "Athy",
      "Bagenalstown",
      "Bailieborough",
      "Balbriggan",
      "Baldoyle",
      "Balgriffin",
      "Ballina",
      "Ballinadee",
      "Ballinasloe",
      "Ballincollig",
      "Ballineen",
      "Ballinrobe",
      "Ballintober",
      "Ballivor",
      "Ballon",
      "Ballsbridge",
      "Ballybrack",
      "Ballybrit",
      "Ballycullen",
      "Ballyfermot",
      "Ballygarvan",
      "Ballyhooly",
      "Ballymahon",
      "Ballymote",
      "Ballymount",
      "Ballymun",
      "Ballyphilip",
      "Ballyragget",
      "Ballyroe",
      "Ballyvaghan",
      "Bandon",
      "Bantry",
      "Berrings",
      "Bettystown",
      "Birr",
      "Blackrock",
      "Blanchardstown",
      "Blessington",
      "Bodyke",
      "Boherbue",
      "Bray",
      "Broadford",
      "Buncrana",
      "Bundoran",
      "Cabinteely",
      "Cabra",
      "Caher",
      "Cahersiveen",
      "Callan",
      "Carbury",
      "Carlow",
      "Carnew",
      "Carraroe",
      "Carrick",
      "Carrick on Shannon",
      "Carrick-on-Suir",
      "Carrickmacross",
      "Carrickmines",
      "Carrigaline",
      "Carrigtohill",
      "Cashel",
      "Castlebar",
      "Castleblayney",
      "Castlebridge",
      "Castleknock",
      "Castlemaine",
      "Castlerea",
      "Cavan",
      "Celbridge",
      "Clane",
      "Clarecastle",
      "Claregalway",
      "Claremorris",
      "Clogherhead",
      "Clonakilty",
      "Clondalkin",
      "Clonee",
      "Clones",
      "Clonmel",
      "Clonsilla",
      "Clontarf",
      "Coachford",
      "Cobh",
      "Coolock",
      "Cork",
      "County Galway",
      "County Wexford",
      "Courtown",
      "Crookhaven",
      "Cross",
      "Crosshaven",
      "Crumlin",
      "Crusheen",
      "Dalkey",
      "Delgany",
      "Donabate",
      "Donegal",
      "Donnybrook",
      "Doolin",
      "Doughiska",
      "Douglas",
      "Drogheda",
      "Droichead Nua",
      "Dublin",
      "Duleek",
      "Dunboyne",
      "Dundalk",
      "Dundrum",
      "Dungarvan",
      "Dunlavin",
      "Dunleer",
      "Dunshaughlin",
      "Edenderry",
      "Enfield",
      "Ennis",
      "Enniscorthy",
      "Enniskerry",
      "Feakle",
      "Ferbane",
      "Fermoy",
      "Finglas",
      "Firhouse",
      "Foxford",
      "Foxrock",
      "Foynes",
      "Galway",
      "Garristown",
      "Geevagh",
      "Glanmire",
      "Glasnevin",
      "Glen",
      "Glenealy",
      "Glengarriff",
      "Glenties",
      "Gorey",
      "Gort",
      "Grange",
      "Greystones",
      "Headford",
      "Hospital",
      "Inchicore",
      "Irishtown",
      "Island",
      "Jamestown",
      "Kanturk",
      "Kells",
      "Kenmare",
      "Kilbride Cross Roads",
      "Kilcock",
      "Kilcoole",
      "Kilcullen",
      "Kildalkey",
      "Kildare",
      "Kilfinane",
      "Kilkenny",
      "Killala",
      "Killaloe",
      "Killarney",
      "Killiney",
      "Killinick",
      "Killorglin",
      "Killurin",
      "Killybegs",
      "Killygordon",
      "Kilmainham",
      "Kilmichael",
      "Kilmore",
      "Kilrush",
      "Kiltamagh",
      "Kingscourt",
      "Kingswood",
      "Kinsale",
      "Kinvarra",
      "Leamlara",
      "Leixlip",
      "Leopardstown",
      "Letterkenny",
      "Limerick",
      "Lisselton",
      "Listowel",
      "Longford",
      "Longwood",
      "Loughrea",
      "Louth",
      "Lucan",
      "Lusk",
      "Macroom",
      "Malahide",
      "Mallow",
      "Manorhamilton",
      "Marino",
      "Maynooth",
      "Mayo",
      "Midleton",
      "Milltown",
      "Mitchelstown",
      "Monaghan",
      "Monasterevin",
      "Monkstown",
      "Mornington",
      "Mount Merrion",
      "Mountrath",
      "Moycullen",
      "Mullinavat",
      "Mullingar",
      "Naas",
      "Naul",
      "Navan",
      "Nenagh",
      "New Ross",
      "Newcastle West",
      "Newmarket",
      "Newport",
      "Oranmore",
      "Oughterard",
      "Oysterhaven",
      "Passage West",
      "Patrickswell",
      "Portarlington",
      "Porterstown",
      "Portmarnock",
      "Portumna",
      "Prosperous",
      "Raheny",
      "Rathcoole",
      "Rathfarnham",
      "Rathgar",
      "Rathmines",
      "Rathmolyon",
      "Rathowen",
      "Ratoath",
      "Ringaskiddy",
      "River",
      "Roscommon",
      "Roscrea",
      "Rush",
      "Saggart",
      "Saint Mullins",
      "Sallins",
      "Sallynoggin",
      "Sandyford",
      "Sandymount",
      "Santry",
      "Seafield",
      "Shankill",
      "Shannon",
      "Shrule",
      "Sixmilebridge",
      "Skerries",
      "Skibbereen",
      "Slieve",
      "Sligo",
      "Spiddal",
      "Stepaside",
      "Stillorgan",
      "Stradbally",
      "Straffan",
      "Summerhill",
      "Sutton",
      "Swinford",
      "Swords",
      "Tallaght",
      "Templeogue",
      "Terenure",
      "Thomastown",
      "Thurles",
      "Tipperary",
      "Tralee",
      "Trim",
      "Tuam",
      "Tullamore",
      "Tullow",
      "Tyrrellspass",
      "Virginia",
      "Walkinstown",
      "Waterford",
      "Westport",
      "Wexford",
      "Wicklow",
      "Williamstown",
      "Windy Arbour",
      "Youghal",
      "Ballaghaderreen",
      "Ballisodare",
      "Ballyhaunis",
      "Bearna",
      "Belmullet",
      "Boyle",
      "Carrick-on-Shannon",
      "Clifden",
      "Collooney",
      "County Leitrim",
      "Crossmolina",
      "Gaillimh",
      "Galway City",
      "Inishcrone",
      "Kinlough",
      "Mayo County",
      "Strandhill",
      "Tobercurry",
      "An Iarmhí",
      "An Longfort",
      "An Mhí",
      "An Muileann gCearr",
      "An Ros",
      "Ashford",
      "Athgarvan",
      "Aughrim",
      "Balally",
      "Ballinroad",
      "Ballinteer",
      "Ballyboden",
      "Ballygerry",
      "Ballylinan",
      "Balrothery",
      "Baltinglass",
      "Banagher",
      "Bayside",
      "Beaumont",
      "Bonnybrook",
      "Booterstown",
      "Bunclody",
      "Carlingford",
      "Castlebellingham",
      "Castlecomer",
      "Castledermot",
      "Castlepollard",
      "Castletown",
      "Chapelizod",
      "Charlesland",
      "Cherry Orchard",
      "Cherryville",
      "Clara",
      "Clonskeagh",
      "Confey",
      "County Carlow",
      "Daingean",
      "Darndale",
      "Derrinturn",
      "Dollymount",
      "Donaghmede",
      "Donnycarney",
      "Dromiskin",
      "Drumcondra",
      "Dublin City",
      "Dún Laoghaire",
      "Dún Laoghaire-Rathdown",
      "Eadestown",
      "Edgeworthstown",
      "Fairview",
      "Ferns",
      "Fingal County",
      "Graiguenamanagh",
      "Granard",
      "Greenhills",
      "Hartstown",
      "Howth",
      "Jobstown",
      "Johnstown",
      "Kentstown",
      "Kilbeggan",
      "Kill",
      "Killester",
      "Kilmacanoge",
      "Kilpedder",
      "Kilquade",
      "Kinnegad",
      "Kinsealy-Drinan",
      "Knocklyon",
      "Lanesborough",
      "Laois",
      "Laytown",
      "Little Bray",
      "Loch Garman",
      "Loughlinstown",
      "Lú",
      "Moate",
      "Mooncoin",
      "Moone",
      "Mountmellick",
      "Newcastle",
      "Newtown Trim",
      "Newtownmountkennedy",
      "Old Kilcullen",
      "Oldbawn",
      "Oldcastle",
      "Palmerstown",
      "Piltown",
      "Portlaoise",
      "Portraine",
      "Rathangan",
      "Rathdowney",
      "Rathdrum",
      "Rathnew",
      "Rathwire",
      "Rialto",
      "Ringsend",
      "Rochfortbridge",
      "Rosslare",
      "Slane",
      "South Dublin",
      "Stamullin",
      "Termonfeckin",
      "Tullyallen",
      "Uíbh Fhailí",
      "Valleymount",
      "Adare",
      "Aghada",
      "An Clár",
      "Annacotty",
      "Ardnacrusha",
      "Askeaton",
      "Ballybunnion",
      "Blarney",
      "Caherconlish",
      "Cahir",
      "Carrigtwohill",
      "Castleconnell",
      "Castleisland",
      "Castlemartyr",
      "Ciarraí",
      "Cill Airne",
      "Cloyne",
      "Cluain Meala",
      "Cork City",
      "County Cork",
      "County Tipperary",
      "Croom",
      "Derry",
      "Dingle",
      "Dunmanway",
      "Dunmore East",
      "Fethard",
      "Killumney",
      "Kilmallock",
      "Luimneach",
      "Millstreet",
      "Moroe",
      "Moyross",
      "Nenagh Bridge",
      "Newmarket on Fergus",
      "Portlaw",
      "Ráth Luirc",
      "Rathcormac",
      "Rathkeale",
      "Templemore",
      "Tower",
      "Trá Mhór",
      "Watergrasshill",
      "Whitegate",
      "An Cabhán",
      "Ballybofey",
      "Ballyconnell",
      "Ballyjamesduff",
      "Ballyshannon",
      "Belturbet",
      "Carndonagh",
      "Convoy",
      "Cootehill",
      "County Donegal",
      "County Monaghan",
      "Derrybeg",
      "Dungloe",
      "Dunlewy",
      "Gweedore",
      "Leifear",
      "Moville",
      "Muff",
      "Mullagh",
      "Newtown Cunningham",
      "Ramelton",
      "Raphoe"
  ]
  res.status(200).json({ cities: cities.sort() });
  }
};
